<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pimentconfig"
 *
 * Auto generated by Extension Builder 2017-11-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Piment Config',
	'description' => 'Configurations supplémentaires pour la plateforme TYPO3',
	'category' => 'plugin',
	'author' => 'Dmitry Vasilev',
	'author_email' => 'info@t3dev.ru',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => [
		'depends' => [
			'typo3' => '10.4.0-10.4.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
);